apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: microservices
  name: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservices
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: microservices
    spec:
      containers:
      - image: pokharia83/microservices:v1
        name: microservices
        command: [ "sleep" ]
        args: [ "infinity" ]
        ports:
          - containerPort: 8081
        resources: {}
status: {}
