apiVersion: v1
kind: Pod for weather API deployment to kubernetes clusters
metadata:
  name: final_weather
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: final_weather
    spec:
      containers:
      - name: final_weather
        image: 641825664234.dkr.ecr.ap-south-1.amazonaws.com/final_weather:latest
        ports:
        - containerPort: 8081
        imagePullPolicy: Always
